"""Windows autostart management with a safe Windows fallback.

Primary strategy: Task Scheduler (ONLOGON + 30s delay).
Fallback strategy: per-user Startup folder with an auto-generated VBS launcher.

This replaces the older HKCU\\...\\Run registry approach, which fires too
early at boot and has no built-in delay.
"""

import logging
import os
import subprocess
import sys
from pathlib import Path

log = logging.getLogger(__name__)

APP_NAME = "flow-st8"
_STARTUP_DELAY = "0000:10"  # MMSS:SS - 10 seconds after login
_STARTUP_DELAY_MS = 10_000
_STARTUP_FOLDER_SCRIPT = "flow-st8-startup.vbs"

# Legacy registry key kept only for migration cleanup
_RUN_KEY = r"Software\Microsoft\Windows\CurrentVersion\Run"


def _run_hidden(command: list[str]) -> subprocess.CompletedProcess[str]:
    """Run a Windows console command without flashing a terminal window."""
    kwargs = {
        "capture_output": True,
        "text": True,
    }
    create_no_window = getattr(subprocess, "CREATE_NO_WINDOW", 0)
    if create_no_window:
        kwargs["creationflags"] = create_no_window
    return subprocess.run(command, **kwargs)


def _resolve_pythonw_command() -> tuple[Path, Path]:
    """Resolve the exact interpreter and entry point we want to launch."""
    main_py = Path(__file__).resolve().parent / "main.py"
    exe = Path(sys.executable)
    pythonw = exe.with_name("pythonw.exe")
    if pythonw.exists():
        exe = pythonw
    return exe, main_py


def _build_command() -> str:
    """Build the command line used by Task Scheduler."""
    exe, main_py = _resolve_pythonw_command()
    return f'"{exe}" "{main_py}"'


def _startup_script_path() -> Path:
    startup_dir = (
        Path(os.environ.get("APPDATA", ""))
        / "Microsoft"
        / "Windows"
        / "Start Menu"
        / "Programs"
        / "Startup"
    )
    return startup_dir / _STARTUP_FOLDER_SCRIPT


def _build_startup_vbs() -> str:
    """Build a Startup-folder VBS launcher with the same 30s delay."""
    exe, main_py = _resolve_pythonw_command()
    script_dir = Path(__file__).resolve().parent
    exe_str = str(exe).replace('"', '""')
    main_py_str = str(main_py).replace('"', '""')
    script_dir_str = str(script_dir).replace('"', '""')
    return "\n".join(
        [
            "' Auto-generated by flow-st8. Starts hidden after login with a short delay.",
            "Set shell = CreateObject(\"WScript.Shell\")",
            f"shell.CurrentDirectory = \"{script_dir_str}\"",
            f"WScript.Sleep {_STARTUP_DELAY_MS}",
            (
                f"shell.Run Chr(34) & \"{exe_str}\" & Chr(34) & \" \" & "
                f"Chr(34) & \"{main_py_str}\" & Chr(34), 0, False"
            ),
            "",
        ]
    )


def _remove_legacy_registry() -> None:
    """Remove old HKCU Run registry entry left from previous versions."""
    try:
        import winreg

        with winreg.OpenKey(
            winreg.HKEY_CURRENT_USER, _RUN_KEY, 0, winreg.KEY_SET_VALUE
        ) as k:
            winreg.DeleteValue(k, APP_NAME)
        log.info("Removed legacy registry autostart entry.")
    except FileNotFoundError:
        pass
    except OSError:
        pass


def _is_task_enabled() -> bool:
    result = _run_hidden(["schtasks", "/query", "/tn", APP_NAME])
    return result.returncode == 0


def _is_startup_folder_enabled() -> bool:
    return _startup_script_path().exists()


def is_enabled() -> bool:
    return _is_task_enabled() or _is_startup_folder_enabled()


def _enable_scheduled_task() -> tuple[bool, str]:
    cmd = _build_command()
    result = _run_hidden(
        [
            "schtasks",
            "/create",
            "/tn",
            APP_NAME,
            "/tr",
            cmd,
            "/sc",
            "ONLOGON",
            "/delay",
            _STARTUP_DELAY,
            "/it",
            "/f",
        ]
    )
    if result.returncode == 0:
        log.info(
            "Autostart enabled (Task Scheduler, 30s delay, interactive): %s",
            cmd,
        )
        return True, ""
    return False, (result.stderr or result.stdout).strip()


def _enable_startup_folder() -> bool:
    path = _startup_script_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(_build_startup_vbs(), encoding="utf-8")
    log.info("Autostart enabled via Startup folder fallback: %s", path)
    return True


def _disable_scheduled_task() -> bool:
    result = _run_hidden(["schtasks", "/delete", "/tn", APP_NAME, "/f"])
    if result.returncode == 0:
        return True

    message = (result.stderr or result.stdout).strip()
    if "cannot find" in message.lower():
        return True

    log.warning(
        "Autostart task delete returned %s: %s",
        result.returncode,
        message,
    )
    return False


def _disable_startup_folder() -> bool:
    path = _startup_script_path()
    try:
        path.unlink()
        log.info("Removed Startup folder fallback launcher.")
        return True
    except FileNotFoundError:
        return True
    except OSError:
        log.exception("Failed to remove Startup folder fallback launcher: %s", path)
        return False


def enable() -> bool:
    _remove_legacy_registry()
    ok, error = _enable_scheduled_task()
    if ok:
        _disable_startup_folder()
        return True

    log.warning(
        "Task Scheduler autostart unavailable, falling back to Startup folder: %s",
        error,
    )
    return _enable_startup_folder()


def disable() -> bool:
    _remove_legacy_registry()
    task_ok = _disable_scheduled_task()
    startup_ok = _disable_startup_folder()
    if task_ok and startup_ok:
        log.info("Autostart fully disabled.")
    return task_ok and startup_ok


def sync(desired: bool) -> None:
    """Ensure Windows autostart matches the desired state."""
    if desired:
        enable()
    else:
        disable()
