# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for the macOS .app bundle.

Build from the repo root (or just run packaging/macos/release.sh):

    pyinstaller packaging/macos/flow-st8-mac.spec

The .icns is generated by release.sh into build/macos/. If it is missing the
bundle still builds, just with the stock PyInstaller icon.
"""

from pathlib import Path

from PyInstaller.utils.hooks import (
    collect_data_files,
    collect_dynamic_libs,
    collect_submodules,
)

ROOT = Path(SPECPATH).resolve().parent.parent
VERSION = (ROOT / "VERSION").read_text(encoding="utf-8").strip()
BUNDLE_ID = "com.luckmattos.flow-st8"

ICNS = ROOT / "build" / "macos" / "flow-st8.icns"
icon = str(ICNS) if ICNS.exists() else None

datas = [
    (str(ROOT / "VERSION"), "."),
    (str(ROOT / "assets" / "flow-st8-icon.png"), "assets"),
]
datas += collect_data_files("silero_vad", includes=["data/*"])
# MLX ships its Metal kernels as mlx/lib/mlx.metallib. PyInstaller treats it as
# an unknown file type and drops it, and without it every GPU op fails at
# runtime — in a bundle that otherwise looks complete.
datas += collect_data_files("mlx", includes=["lib/*.metallib"])
datas += collect_data_files("whisper", includes=["assets/*"])

# libmlx.dylib links libjaccl.dylib through @rpath. PyInstaller follows the
# first but not the second, and the bundle then dies at `import mlx.core` with
# "Library not loaded: @rpath/libjaccl.dylib".
binaries = collect_dynamic_libs("mlx")

hiddenimports = [
    "sounddevice",
    "pyperclip",
    "silero_vad.data",
    # mlx.core imports helpers like mlx._reprlib_fix at extension-init time,
    # which static analysis never sees. Without them the bundle raises a bare
    # "Encountered an error while initializing the extension".
    *collect_submodules("mlx"),
    *collect_submodules("mlx_whisper"),
    # backends/__init__.py picks the shell behind `if sys.platform`, and the
    # macOS one talks to AppKit/Quartz through pyobjc. Uncomment as
    # backends/macos/ lands — PyInstaller does not reliably follow either.
    # "backends.macos.autostart",
    # "backends.macos.hotkey",
    # "backends.macos.injector",
    # "backends.macos.overlay",
    # "backends.macos.tray",
    # "AppKit",
    # "Quartz",
    # "objc",
]


a = Analysis(
    [str(ROOT / "main.py")],
    pathex=[str(ROOT)],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    # Once transcription on macOS moves to MLX, add "torch" here: it is the
    # single biggest contributor to bundle size (~1.5 GB on its own).
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="flow-st8",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,  # upx corrupts signed Mach-O binaries
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch="arm64",
    # Signing is done by release.sh so the same spec works signed or unsigned.
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name="flow-st8",
)

app = BUNDLE(
    coll,
    name="flow-st8.app",
    icon=icon,
    bundle_identifier=BUNDLE_ID,
    version=VERSION,
    info_plist={
        "CFBundleName": "flow-st8",
        "CFBundleDisplayName": "flow-st8",
        "CFBundleShortVersionString": VERSION,
        "CFBundleVersion": VERSION,
        # Menu-bar only app: no Dock icon, no app switcher entry.
        "LSUIElement": True,
        "LSMinimumSystemVersion": "14.0",
        "NSHighResolutionCapable": True,
        "LSApplicationCategoryType": "public.app-category.productivity",
        # Required. Without it macOS kills the process when it asks for the mic.
        "NSMicrophoneUsageDescription": (
            "O flow-st8 usa o microfone para transcrever sua voz localmente. "
            "Nenhum áudio sai do seu computador."
        ),
        # Accessibility (global hotkey + paste) has no Info.plist key: the app
        # requests it at runtime via AXIsProcessTrustedWithOptions.
    },
)
